import type { AminoAcidCode, AminoAcidProfile } from '../../types/variant'

export const aminoAcids: Record<AminoAcidCode, AminoAcidProfile> = {
  A: { code: 'A', name: 'Alanine', polarity: 'nonpolar', charge: 'neutral', size: 'small', hydropathy: 1.8 },
  R: { code: 'R', name: 'Arginine', polarity: 'basic', charge: 'positive', size: 'large', hydropathy: -4.5 },
  N: { code: 'N', name: 'Asparagine', polarity: 'polar', charge: 'neutral', size: 'medium', hydropathy: -3.5 },
  D: { code: 'D', name: 'Aspartate', polarity: 'acidic', charge: 'negative', size: 'medium', hydropathy: -3.5 },
  C: { code: 'C', name: 'Cysteine', polarity: 'polar', charge: 'neutral', size: 'medium', hydropathy: 2.5 },
  Q: { code: 'Q', name: 'Glutamine', polarity: 'polar', charge: 'neutral', size: 'large', hydropathy: -3.5 },
  E: { code: 'E', name: 'Glutamate', polarity: 'acidic', charge: 'negative', size: 'large', hydropathy: -3.5 },
  G: { code: 'G', name: 'Glycine', polarity: 'nonpolar', charge: 'neutral', size: 'small', hydropathy: -0.4 },
  H: { code: 'H', name: 'Histidine', polarity: 'basic', charge: 'positive', size: 'large', hydropathy: -3.2 },
  I: { code: 'I', name: 'Isoleucine', polarity: 'nonpolar', charge: 'neutral', size: 'large', hydropathy: 4.5 },
  L: { code: 'L', name: 'Leucine', polarity: 'nonpolar', charge: 'neutral', size: 'large', hydropathy: 3.8 },
  K: { code: 'K', name: 'Lysine', polarity: 'basic', charge: 'positive', size: 'large', hydropathy: -3.9 },
  M: { code: 'M', name: 'Methionine', polarity: 'nonpolar', charge: 'neutral', size: 'large', hydropathy: 1.9 },
  F: { code: 'F', name: 'Phenylalanine', polarity: 'nonpolar', charge: 'neutral', size: 'large', hydropathy: 2.8 },
  P: { code: 'P', name: 'Proline', polarity: 'nonpolar', charge: 'neutral', size: 'medium', hydropathy: -1.6 },
  S: { code: 'S', name: 'Serine', polarity: 'polar', charge: 'neutral', size: 'small', hydropathy: -0.8 },
  T: { code: 'T', name: 'Threonine', polarity: 'polar', charge: 'neutral', size: 'medium', hydropathy: -0.7 },
  W: { code: 'W', name: 'Tryptophan', polarity: 'nonpolar', charge: 'neutral', size: 'large', hydropathy: -0.9 },
  Y: { code: 'Y', name: 'Tyrosine', polarity: 'polar', charge: 'neutral', size: 'large', hydropathy: -1.3 },
  V: { code: 'V', name: 'Valine', polarity: 'nonpolar', charge: 'neutral', size: 'medium', hydropathy: 4.2 },
}

export const threeToOne: Record<string, AminoAcidCode> = {
  ALA: 'A',
  ARG: 'R',
  ASN: 'N',
  ASP: 'D',
  CYS: 'C',
  GLN: 'Q',
  GLU: 'E',
  GLY: 'G',
  HIS: 'H',
  ILE: 'I',
  LEU: 'L',
  LYS: 'K',
  MET: 'M',
  PHE: 'F',
  PRO: 'P',
  SER: 'S',
  THR: 'T',
  TRP: 'W',
  TYR: 'Y',
  VAL: 'V',
}
