import {
  BookOpenText,
  CalendarDays,
  Castle,
  CircleAlert,
  CircleCheckBig,
  Clock3,
  CloudLightning,
  Coins,
  Download,
  Flame,
  FlaskConical,
  Hammer,
  Hourglass,
  Info,
  Landmark,
  LockKeyhole,
  Map,
  Pause,
  Pickaxe,
  Play,
  RotateCcw,
  ScrollText,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Skull,
  Sparkles,
  Store,
  Sun,
  Swords,
  Target,
  Telescope,
  Trash2,
  TrendingUp,
  Trophy,
  Upload,
  Volume2,
  VolumeX,
  Wheat,
  X,
  Zap,
} from 'lucide-react';

// Central icon registry keeps every game symbol visually consistent and code-native.
const ICONS = {
  BookOpenText,
  CalendarDays,
  Castle,
  CircleAlert,
  CircleCheckBig,
  Clock3,
  CloudLightning,
  Coins,
  Download,
  Flame,
  FlaskConical,
  Hammer,
  Hourglass,
  Info,
  Landmark,
  LockKeyhole,
  Map,
  Pause,
  Pickaxe,
  Play,
  RotateCcw,
  ScrollText,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Skull,
  Sparkles,
  Store,
  Sun,
  Swords,
  Target,
  Telescope,
  Trash2,
  TrendingUp,
  Trophy,
  Upload,
  Volume2,
  VolumeX,
  Wheat,
  X,
  Zap,
};

// Renders a named Lucide icon with shared stroke and accessibility defaults.
export function GameIcon({ name, size = 20, strokeWidth = 1.7, ...props }) {
  const Icon = ICONS[name] || Sparkles;
  return <Icon aria-hidden="true" size={size} strokeWidth={strokeWidth} {...props} />;
}
